import type { LucideIcon } from "lucide-react";
import {
  Bell,
  BookOpen,
  GitCompare,
  Home,
  Landmark,
  MoreHorizontal,
  Receipt,
  Route,
  Search,
  Settings,
  Shield,
  UserPlus,
  Wallet,
  Wrench,
} from "lucide-react";

/** Lucide is already in-tree — nav marks only. Never a second Compass. */
export const V4_NAV_ICONS: Record<string, LucideIcon> = {
  Home,
  Money: Wallet,
  Path: Route,
  Compare: GitCompare,
  "Ask HōMI": Search,
  Bills: Receipt,
  Tools: Wrench,
  Learn: BookOpen,
  Accounts: Landmark,
  Settings,
  Attention: Bell,
  Privacy: Shield,
  Book: BookOpen,
  Invite: UserPlus,
  Users: UserPlus,
  Organizations: Landmark,
  Assessments: BookOpen,
  Activity: Bell,
  Marketing: BookOpen,
  Analytics: GitCompare,
  Attribution: Route,
  Email: Receipt,
  "Ad spend": Wallet,
  Waitlist: Bell,
  More: MoreHorizontal,
};
